version: "3.3"

services:
  flyway:
    build:
      context: .
    image: flyway-template
    restart: "no"
    command: migrate
    environment:
      ENVIRONMENT: "tst"
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - my_network

  db:
    image: postgres:10
    restart: "no"
    environment:
      POSTGRES_PASSWORD: "my_password"
      POSTGRES_USER: "my_username"
      POSTGRES_DB: "my_database"
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - my_network

networks:
  my_network:
